---
.gitignore:
  required:
    - ---.project

.gitlab-ci.yml:
  delete: true

.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml

.travis.yml:
  unmanaged: true

appveyor.yml:
  unmanaged: true

spec/default_facts.yml:
  unmanaged: true

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true